### PR TITLE
[ESI] Use new ParameterAttr for module parameters

### PR DESCRIPTION
**Pull request by youngar**
This fixes a compilation error in the integration test where ESI was not
switched to use a new dedicated ParameterAttr introduced in 471e60ce.

### CODE REVIEW

**Comment by youngar** [comment]
Compilation tested locally, but the integration tests aren't passing.  I don't think I have it set up properly:
```
Exception: The ESI cosimulation DPI library must be enabled to run cosim tests.
```
```
  CIRCT :: ESI/cosim/basic.mlir
  CIRCT :: ESI/cosim/cosim_only.sv
  CIRCT :: ESI/cosim/loopback.mlir
  ```

**Comment by youngar** [comment]
Looks like there needs to be some work to get this working on OSX?  The library name is not correct:
```
> grep "ESI_COSIM" ./CMakeCache.txt
ESI_COSIM:BOOL=ON

> grep config.esi_cosim_path ./tools/circt/integration_test/lit.site.cfg.py
config.esi_cosim_path = "/Users/andrewy/wsp/circt/build-release/lib/libEsiCosimDpiServer.so"

ls /Users/andrewy/wsp/circt/build-release/lib/libEsiCosimDpiServer.so
ls: /Users/andrewy/wsp/circt/build-release/lib/libEsiCosimDpiServer.so: No such file or directory

find . -iname "*esicosim*"
./tools/circt/include/circt/Dialect/ESI/cosim/CMakeFiles/EsiCosimCapnp.dir
./tools/circt/lib/Dialect/ESI/cosim/cosim_dpi_server/CMakeFiles/EsiCosimDpiServer.dir
./lib/libEsiCosimCapnp.a
./lib/libEsiCosimDpiServer.dylib
```

**Comment by teqdruid** [comment]
Thanks! Looks like Chris moved over to builders an forgot these.

**Comment by lattner** [comment]
Oh thanks for catching this.  This pass has a bunch of code hidden behind an ifdef.  Is there any way to get the bulk of it outside the ifdef so those of us without the dependencies are still at least building the code?

**Comment by teqdruid** [comment]
Not logically -- we need Capnp to determine the bitwidth of types. It just
occurred to me, however, that we could use nonsense values if we don't have
capnp available to do the construction outside of the #ifdefs to
achieve both goals.
