### ISSUE TITLE
Windows build break: unresolved external symbol __imp_mlirGetDialectHandle__rtl__

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#578]
```
ir.obj : error LNK2019: unresolved external symbol __imp_mlirContextRegisterRTLDialect referenced in function main [D:\a\circt\circt\build_release\test\CAPI\circt-capi-ir-test.vcxproj]
ir.obj : error LNK2019: unresolved external symbol __imp_mlirContextLoadRTLDialect referenced in function main [D:\a\circt\circt\build_release\test\CAPI\circt-capi-ir-test.vcxproj]
ir.obj : error LNK2019: unresolved external symbol __imp_mlirRTLDialectGetNamespace referenced in function main [D:\a\circt\circt\build_release\test\CAPI\circt-capi-ir-test.vcxproj]
D:\a\circt\circt\build_release\bin\circt-capi-ir-test.exe : fatal error LNK1120: 3 unresolved externals [D:\a\circt\circt\build_release\test\CAPI\circt-capi-ir-test.vcxproj]
```

Likely broken by b03db32b0f83824306c301b68ad02cb5a7af04b8. @GeorgeLyon Could you take a look please?

**Comment by GeorgeLyon** [comment]
I think the patch updating MLIR will fix this, not sure how this sneaked past CI

**Comment by GeorgeLyon** [comment]
Looks like @youngar fixed that patch, thanks Andrew! I've merged that PR and am re-running the windows build.

**Comment by teqdruid** [comment]
the CI doesn't run the Windows build. It's run nightly. Not ideal, but we have a limited number of builders and the windows build is pretty slow, especially when compiling LLVM.

**Comment by teqdruid** [comment]
Thanks!

**Comment by GeorgeLyon** [comment]
Looks like the build failed but with a different error: https://github.com/llvm/circt/runs/1881924297?check_suite_focus=true

**Comment by teqdruid** [comment]
That's probably an under specification of the dependencies for the CAPI library or test.

**Comment by GeorgeLyon** [comment]
The only dependency that should be needed for that symbol is this: https://github.com/llvm/circt/blob/162a0d824796c8423af0aa1dbf5e55257251ccd2/test/CAPI/CMakeLists.txt#L9
Indeed, that should be the only symbol in that target: https://github.com/llvm/circt/blob/162a0d824796c8423af0aa1dbf5e55257251ccd2/lib/CAPI/Dialect/RTL.cpp#L19

The "inconsistent visibility" message is curious too. I'm not sure how that is the case, though I am unfamiliar with Windows.
This is where it is declared:

https://github.com/llvm/llvm-project/blob/74916008a87dd2992d12af0b9725cb1804d0c8ba/mlir/include/mlir-c/Registration.h#L41
And this is where the definition is:

https://github.com/llvm/llvm-project/blob/2996a8d67553b9d469e01215b49bb1af17ad6d1e/mlir/include/mlir/CAPI/Registration.h#L48

**Comment by GeorgeLyon** [comment]
@teqdruid Thinking about this a bit more, I'm wondering if the `MLIR_CAPI_EXPORTED` define isn't being set properly for some reason in one of the configurations. That would explain the "inconsistent visibility" message (one version has it correct and another has it incorrect), and incorrect visibility would explain why a symbol which seems to be pretty straightforwardly defined in a dependency, is not found. I'm not really sure how to test this theory in the Windows build.

**Comment by teqdruid** [comment]
> The "inconsistent visibility" message is curious too. I'm not sure how that is the case, though I am unfamiliar with Windows

Where are you seeing this message?

I am also not terribly familiar with development on Windows.

**Comment by GeorgeLyon** [comment]
Whoops, I misspoke, the log was not "inconsistent visibility" but "inconsistent dll linkage"
https://github.com/llvm/circt/runs/1881924297?check_suite_focus=true#step:7:171

**Comment by teqdruid** [comment]
I see it now. I've had trouble with dynamic vs static linking on windows before with LLHD.

**Comment by teqdruid** [comment]
I've repro'd the issue locally and established that if that function is exported properly with `__declspec(dllexport)` it links. (I hacked the header in llvm.) So you were correct about the capi exported being wrong.

**Comment by teqdruid** [comment]
Ah... https://github.com/llvm/llvm-project/blob/4d3a061c32ee5c4fb88be389a4dd7fd71fc9fa9c/mlir/lib/CAPI/Dialect/CMakeLists.txt#L10 probably sets the macros properly.

**Comment by teqdruid** [comment]
switching to `add_mlir_public_c_api_library` didn't fix the linker error :(

**Comment by GeorgeLyon** [comment]
:( sorry this has become such an issue. If it ends up making sense to kick the can down the road, we can always put that macro directly into RTL.h (along with some lengthy prose) to guarantee it does the right thing.

**Comment by GeorgeLyon** [comment]
OK, so `add_mlir_public_c_api_library` is on the right track, but it seems that some additional work happens here:
https://github.com/llvm/llvm-project/blob/5631842d181016207e85e4d035d0c4383f34337a/mlir/lib/CAPI/CMakeLists.txt#L11

If I'm understanding correctly, this will run _before_ the RTL dialect C API is added to MLIR_PUBLIC_C_API_LIBS (thanks, cmake). Maybe there is something we need to do in order to get those symbols into the shared library?

**Comment by teqdruid** [comment]
It seems to me we have two handicaps: 1) nobody involved knows how cmake works and 2) nobody understands C++ development on Windows.

Let's just keep this issue open until someone has the time and willingness to look deeper into this rabbit hole.

**Comment by teqdruid** [comment]
I just checked this test again and it works on Windows now! I suspect it was one of @mikeurbach's recent cleanup changes.

**Comment by mikeurbach** [comment]
Nice! The layers are slowly starting to align, so I guess that is going to appease the Windows gods.

**Comment by teqdruid** [comment]
Yeah, so I'm starting to pay attention to windows.
