### ISSUE TITLE
FIRRTL versioning update introduces compilation error

### ISSUE THREAD

**Issue by mortbopet** [llvm/circt#5868]
Introduced by eefcce8509a575e03b4b9874463683f3b97e8920 it seems like the chosen major/minor names alias with macros defined in the GNU C <sys/sysmacros.h> header, thus resulting in failed compilation.

```
/home/mpetersen/circt/include/circt/Dialect/FIRRTL/FIRParser.h:82:9: warning: In the GNU C Library, "major" is defined by 
<sys/sysmacros.h>. For historical compatibility, it is currently defined by <sys/types.h> as well, but we plan to remove this soon. To 
use "major", include <sys/sysmacros.h> directly. If you did not intend to use a system-defined macro "major", you should undefine it
 after including <sys/types.h>. [-W#pragma-messages]
      : major(major), minor(minor), patch(patch) {}

...

/home/mpetersen/circt/include/circt/Dialect/FIRRTL/FIRParser.h:82:9: error: member initializer 'gnu_dev_major' does not name a
 non-static data member or base class
      : major(major), minor(minor), patch(patch) {}
        ^~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/sys/sysmacros.h:101:44: note: expanded from macro 'major'
# define major(dev) __SYSMACROS_DM (major) gnu_dev_major (dev)
                                           ^~~~~~~~~~~~~~~~~~~
In file included from /home/mpetersen/circt/lib/Dialect/FIRRTL/Export/FIREmitter.cpp:15:
/home/mpetersen/circt/include/circt/Dialect/FIRRTL/FIRParser.h:82:23: error: member initializer 'gnu_dev_minor' does not name
 a non-static data member or base class
      : major(major), minor(minor), patch(patch) {}
                      ^~~~~~~~~~~~
...
```

I could insert the `#undefs` but will let @rwy7 decide whether that's the desired solution or if a name change is warranted.

P.s. - who the hell writes a system library with macros defined as `major/minor`?!?!

**Comment by rwy7** [comment]
Thanks for the report! I'll fix it shortly!
